### ISSUE TITLE
How can I force only dates and no time selector?

### ISSUE THREAD

**Issue by toni-moreno** [Eonasdan/bootstrap-datetimepicker#1023]
Hi  @Eonasdan 

I'm testing this promising tool, and I need some times choose date and time in that format "dd/mm/yyyy hh:mm"

but sometimes I need to close to choose only date ( no time ) in this format "dd/mm/yyyy" but I'm not able to do it.

How can I switch from "date+time" mode to ony "date" mode?

Thank you very much !!

**Comment by Eonasdan** [comment]
the [`format`](http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#format) string is what determines what components are used. It takes all valid momentjs format strings.

**Comment by toni-moreno** [comment]
I can't understand how to do it.

after I've created my datetimerpicker with:
```
$("#dt1").datetimepicker({ format: "DD/MM/YYYY HH:mm"});
```
And I've switched to only dates by executing:
```
$("#dt1").datetimepicker({ format: "DD/MM/YYYY"});
```
and also that.
```
$("#dt1").datetimepicker().format("DD/MM/YYYY");
```` 
but , it still continues showing format with time and I can still choose time with the control.


![image](https://cloud.githubusercontent.com/assets/5883405/7311939/83ff860a-ea43-11e4-8c66-4e3e208854b9.png)

What I'm doing wrong ?

**Comment by nikoskalogridis** [comment]
If you execute all three commands on the same element you actually creating three datetimepicker's attached to that element. After creation you should reference the actual datetimepicker attached to the element as follows:
```
$("#dt1").data("DateTimePicker").format("DD/MM/YYYY")
```

**Comment by toni-moreno** [comment]
this line give me an error.

```
Uncaught TypeError: $(...).data(...).format is not a function
```
I'm working with  DataTimePicker Version 3.0.0.  and Jquery 1.11.0.

**Comment by nikoskalogridis** [comment]
You are using 3.0.0 for a reason? There are a lot of problems with this version. You should at least use latest update of version 3 of the component. Also have a look on version 3 documentation

**Comment by toni-moreno** [comment]
Hi @Eonasdan , @nikoskalogridis 

this version Is a requirement of the product, I don't know If I can update easily.
how can I get a reference for the datetimerpicker object on version 3.0.0 ? Where can I look for documentation for this version ?

**Comment by nikoskalogridis** [comment]
you should use the latest version of the component as version 3 is deprecated. At least upgrade to v3.1.3. There are some serious bugs in v.3.0.0 that will probably trouble you. Look at the version3 branch to obtain the v3 code.

Setting the configuration options after instance creation is not supported in version 3. 

You should use pickTime: false configuration parameter in version 3. Accessing the datetimepicker instance is the same one 
```
$(element).data('DateTimePicker')
```
as for the v3 documentation @Eonasdan should be able to help you with that

**Comment by toni-moreno** [comment]
I need reconfigure after creation, so I will test v4 ,  but I need IE8 support, has v4 been tested on IE8 ?

**Comment by nikoskalogridis** [comment]
Officially there is no support for old IE versions. That told you could have a look on the following link:

http://eonasdan.github.io/bootstrap-datetimepicker/Extras/#ie-7

**Comment by mehtayash** [comment]
Tochoose only date, pass pickTime: false

$('.datetimepicker').datetimepicker({ 
 pickTime: false, 
format:'DD/MM/ YYYY' 
});

**Comment by toni-moreno** [comment]
Hi @nikoskalogridis , @Eonasdan , @mehtayash 

When tested last version (4.7.14) on IE8, the browser  crashed with this error.

![image](https://cloud.githubusercontent.com/assets/5883405/7344857/e6d834fa-eccf-11e4-9493-bdc5776e46e5.png).

I will try with both versions:

```
    <!--[if gte IE 9]>-->
    <script type="text/javascript" src="js/bootstrap.datetimerpicker_v4.js"></script>
    <!--<![endif]-->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="js/bootstrap.datetimerpicker_v3.js"></script>
    <![endif]-->
```

When working with v3 , I will try to switch from "DD/MM/YYY HH:mm" to "DD/MM/YYYY" destroying object and recreating them as @mehtayash suggested 

how can I destroy a previously created datetimepicker object ?

Thank you very much.

**Comment by toni-moreno** [comment]
@nikoskalogridis .

When updated from v3.0.0 to v3.1.3 script crashes on default configuration definition.

The message thrown is somethin like "the object 

"The Object doesn't accept this property or method"


![image](https://cloud.githubusercontent.com/assets/5883405/7347128/7e65b378-ece5-11e4-9757-68f880ed9618.png)

**Comment by toni-moreno** [comment]
Hi to all @Eonasdan @nikoskalogridis  do you know why this object is doing this error? "The Object doesn't accept this property o method"  ?? 

Thank you very much !!

**Comment by liammoat** [comment]
@toni-moreno I have ran into some of these problems. You need to polyfill a couple of methods that IE8 does not support. There could well be more, but I've found you need to include at least these three:

String.prototype.trim()
```
if (!String.prototype.trim) {
  (function() {
    // Make sure we trim BOM and NBSP
    var rtrim = /^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;
    String.prototype.trim = function() {
      return this.replace(rtrim, '');
    };
  })();
}
```

Array.prototype.indexOf()
```
// Production steps of ECMA-262, Edition 5, 15.4.4.14
// Reference: http://es5.github.io/#x15.4.4.14
if (!Array.prototype.indexOf) {
  Array.prototype.indexOf = function(searchElement, fromIndex) {

    var k;

    // 1. Let O be the result of calling ToObject passing
    //    the this value as the argument.
    if (this == null) {
      throw new TypeError('"this" is null or not defined');
    }

    var O = Object(this);

    // 2. Let lenValue be the result of calling the Get
    //    internal method of O with the argument "length".
    // 3. Let len be ToUint32(lenValue).
    var len = O.length >>> 0;

    // 4. If len is 0, return -1.
    if (len === 0) {
      return -1;
    }

    // 5. If argument fromIndex was passed let n be
    //    ToInteger(fromIndex); else let n be 0.
    var n = +fromIndex || 0;

    if (Math.abs(n) === Infinity) {
      n = 0;
    }

    // 6. If n >= len, return -1.
    if (n >= len) {
      return -1;
    }

    // 7. If n >= 0, then Let k be n.
    // 8. Else, n<0, Let k be len - abs(n).
    //    If k is less than 0, then let k be 0.
    k = Math.max(n >= 0 ? n : len - Math.abs(n), 0);

    // 9. Repeat, while k < len
    while (k < len) {
      // a. Let Pk be ToString(k).
      //   This is implicit for LHS operands of the in operator
      // b. Let kPresent be the result of calling the
      //    HasProperty internal method of O with argument Pk.
      //   This step can be combined with c
      // c. If kPresent is true, then
      //    i.  Let elementK be the result of calling the Get
      //        internal method of O with the argument ToString(k).
      //   ii.  Let same be the result of applying the
      //        Strict Equality Comparison Algorithm to
      //        searchElement and elementK.
      //  iii.  If same is true, return k.
      if (k in O && O[k] === searchElement) {
        return k;
      }
      k++;
    }
    return -1;
  };
}
```

Array.prototype.reduce()
```
// Production steps of ECMA-262, Edition 5, 15.4.4.21
// Reference: http://es5.github.io/#x15.4.4.21
if (!Array.prototype.reduce) {
  Array.prototype.reduce = function(callback /*, initialValue*/) {
    if (this == null) {
      throw new TypeError('Array.prototype.reduce called on null or undefined');
    }
    if (typeof callback !== 'function') {
      throw new TypeError(callback + ' is not a function');
    }
    var t = Object(this), len = t.length >>> 0, k = 0, value;
    if (arguments.length === 2) {
      value = arguments[1];
    } else {
      while (k < len && !(k in t)) {
        k++;
      }
      if (k >= len) {
        throw new TypeError('Reduce of empty array with no initial value');
      }
      value = t[k++];
    }
    for (; k < len; k++) {
      if (k in t) {
        value = callback(value, t[k], k, t);
      }
    }
    return value;
  };
}
```
