### ISSUE TITLE
No longer works with jquery 3.0.0 or 3.1.0

### ISSUE THREAD

**Issue by steveyj79** [Eonasdan/bootstrap-datetimepicker#1714]
The library no longer works with jquery 3.0.0 or 3.1.0

**Comment by stuharvey** [comment]
Can you provide a [jsfiddle](https://jsfiddle.net/)? Which version of the library are you using?

**Comment by Fox4305** [comment]
look like it's because $.fn.size() method has been removed from jquery 3.x... 

got that error: bootstrap-datetimepicker.min.js:formatted:1Uncaught TypeError: g.size is not a function

**Comment by steveyj79** [comment]
i'm using the latest version of both librarys

jquery = 3.1.0
bootstrap-datetime =  version : 4.17.37

i'll try and put up a jsfiddle for you tomorrow... but in short the calendar never shows when you click either the calendar button or clicking on the input field so you can never see the date selector

**Comment by Hobadee** [comment]
I can confirm the same issue here.

I got bootstrap-datetimepicker from bower and it installed the latest jquery.  (3.1.0)  Inserting the sample code into a blank page yielded the following JS console error:
`Uncaught TypeError: input.size is not a function
`

I rolled back jquery to 2.2.4 and the datepicker instantly worked.

**Comment by steveyj79** [comment]
i think there is a fix in place 

https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1664

**Comment by steveyj79** [comment]
we have a fix in place and hopefully will get merged https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1726

**Comment by saschaende** [comment]
I can also confirm this

**Comment by jnm2** [comment]
How soon will this fix be available on NuGet?

**Comment by steveyj79** [comment]
No idea, juist waiting for the next release but i have no idea when that will be

**Comment by jnm2** [comment]
Can we get a hotfix in the meantime?

**Comment by steveyj79** [comment]
i'm not the owner of this library :), but theres plenty of approaches you can take if you can't wait for the patch. i don't personally recommend doing any of them and i would wait for the next release. but here goes:

1. Use jquery 2.1.4 or any of the jquery libs before 3++ and wait till 4.17.42 or greater is launched
2. Make the changes locally on your own version of the library and replace once the new library has launched
3. Download the development version of the library which has the fix in place (don't recommend this to highly as the development branch could be unstable)

**Comment by jnm2** [comment]
This is my workaround for now:

```javascript
Object.getPrototypeOf($('#one-of-the-date-pickers')).size = function() { return this.length; }; // Workaround for https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1714
```

But it would be good for the importance of a hotfix to come to @Eonasdan's attention.

**Comment by steveyj79** [comment]
yeah he's been mentioned a few times on the pr where the fix was initially please check here
https://github.com/Eonasdan/bootstrap-datetimepicker/pull/1726

**Comment by Eonasdan** [comment]
dev is now master

**Comment by steveyj79** [comment]
Thank you

**Comment by Fox4305** [comment]
Thanks ! :)

**Comment by Unterdrucker** [comment]
I think Bower users (like me) waiting for version with fix too :)

**Comment by nmcclay** [comment]
Can confirm this is broken in ember 2.8+ which uses jQuery 3+

**Comment by udhaya2089** [comment]
.datepicker is not working in jquery 3.1.1 version.. plz help me guys to get rid of this..

**Comment by evil-shrike** [comment]
@Eonasdan Hi, does closing the issue mean that the library is compatible with jQuery 3.x now?

**Comment by osbeug001** [comment]
For bower users who are not aware, there is version 4.17.45 which works.
