### ISSUE TITLE
Not Working with jQuery 3.5.1

### ISSUE THREAD

**Issue by nikolayganovski1** [Eonasdan/bootstrap-datetimepicker#2317]
Not Working with jQuery 3.5.1, it says Uncaught TypeError: g.size is not a function

**Comment by SparkCat23** [comment]
did you check the order of the <script> tags? Same happened with me.
It should be something like this:
`<script src="sourcePath/jquery-3.5.1.js"></script>
<script src="sourcePath/moment.min.js"></script>
<script src="sourcePath/bootstrap-datetimepicker.min.js"></script>`

Do notice that it requires moment.js to work

**Comment by difelice** [comment]
@nikolayganovski1  make sure to upgrade to version `4.17.47`.
